### PR TITLE
Changes for opensearch 2.6

### PR DESCRIPTION
**Pull request by italo-addsearch**
@aparo could you please review?

### CODE REVIEW

**Comment by italo-addsearch** [comment]
The project works with JDK 15.

I've tried JDK 17 but got this error when running gradle build
```
* What went wrong:
Execution failed for task ':licenseHeaders'.
> java.lang.ClassCastException: class org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to class org.apache.xerces.xni.parser.XMLParserConfiguration (org.apache.xerces.parsers.XIncludeAwareParserConfiguration is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @6a72c479; org.apache.xerces.xni.parser.XMLParserConfiguration is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @74750256)
```

I haven't tried with other JDKs

**Comment by arcoyk** [comment]
Hi! Thank you for the great contribution. Do you have any update on this?

**Comment by italo-addsearch** [comment]
@arcoyk hi! and thank you.
No update. This has been waiting for review for a long time.

**Comment by italo-addsearch** [comment]
@arcoyk merged

**Pull request merged**
